import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TenantFavicon from '@/components/tenant-favicon';
import { getTenantPublicServer } from '@/lib/tenantServer';
import { resolveTenantAsset } from '@/lib/tenant';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
});


export async function generateMetadata(): Promise<Metadata> {
  const tenant = await getTenantPublicServer();
  const icon = resolveTenantAsset(tenant?.faviconUrl || tenant?.logoUrl);

  return {
    title: tenant?.name || 'Reforço escolar',
    description: 'Generated by create next app',
    icons: icon ? { icon } : undefined,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Não forçar redirect aqui — middleware protege rotas `/main`.
  const tenant = await getTenantPublicServer();
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased`}>
        <TenantFavicon initialTenant={tenant} />
        {children}
      </body>
    </html>
  );
}
